language: rust
rust:
- stable
script:
- cargo build --release --manifest-path gitrs_server/Cargo.toml --verbose --all
cache: cargo
matrix:
  include:
  - os: linux
    env: TARGET=x86_64-unknown-linux-gnu
  - os: osx
    env: TARGET=x86_64-apple-darwin
before_install:
- nvm install 8
- nvm use 8
- npm i -g npm@6.1.0
- npm ci --prefix ./ci
before_deploy:
- node ./ci/checkTomlSemver.js
- node ./ci/buildRelease.js
after_success:
- node ./ci/checkIsRelease.js && DO_DEPLOY=true || true
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: eALDh9y1T3WdPOekCS9yocrSohP5nxou2cfijDZgkgV7KnuB3fY01lJg0GV8+Jt7tnamgzn0PCD3dw3TYc6GdRO3vzLUcmB6F+IW/g+kucIFVfpj4cgsFTPBefHxPsmmaEa9tB3P9gObL4gz6R1UF9BrtFm4Ix+5YC9Lwe9wJNVZd/GqdbnBYjFqmCvoKJHXdu0bFB2w46ZednFuHpz7Le/5tnKpzLi7vA5FDbrhEIrFWT6NQSijJ6S/6M8e1LkLLS3+soxqwyA4i0fYEJAcqtHBfbdXXJbk8hnEY41A0Rx28hZi+JJmNAElyYBtpQp0vWJ3ZR3okbUWTrQmU6L+N+n4ninLqlAuseqPiY9dCYFZGeeN0+HwLYeSq8sc3YXRHPQKMfB5/Es1lR7tnTf76vA3eyUmADCIskn/loi7PMBxflZ2nUW4sHAuD9gg5/ikQzrk/+QxVN/CCSQix/l9lnUKfi/oHFc6KMeaUHuMgcHBia0LcdNE2nflIV1XZn08PQuycQ0qyPi5v/26tyPhQYF4pqwRlGLwoP7zwNmOCLpBw7oOJs++gFuYsXywb0SlZ26zBg7FEKVI7Q0YT4KobUq3ASDIAt1ZcL/YkSK4K0n/z3YWwWIzR76g+YVfFQ1PNZHbTmXni/eRf3bt4Pxydbq6ARO8mEmUrB5RQlvo/EA=
  file: "$TARGET.tar.gz"
  on:
    repo: stevek-axo/git-rs
    tags: true
    condition: "$DO_DEPLOY"
