[package]
name = "git_server"
version = "0.1.0"
authors = [
  "Tyler Wanek <tylerw@axosoft.com>",
  "Joshua Grosso <joshuag@axosoft.com>",
  "Jose Garcia <joseg@axosoft.com>",
  "Brandon Quan <brandonq@axosoft.com>"
]

[dependencies]
